sudo: false
distr : "trusty"

language: generic

before_install:

  # Install python
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

 # pytest
  - conda install -c anaconda pytest
  - conda install -c conda-forge pytest-cov
  - conda install python=3.6

  # codacy-coverage
  - pip install -q --upgrade pip
  - pip install -q coverage
  - pip install -q codacy-coverage
  - pip install -q coveralls


install:
  - pip install -qe .[test]

script:
  - cd test/
  - pytest --cov=deeprank --cov-report xml:coverage.xml
  - mv coverage.xml ../
  - mv .coverage ../
  - cd ../

after_script:
- python-codacy-coverage -r coverage.xml
- coveralls
